# Generated by Django 3.2.8 on 2021-11-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='scheduled_departure_date',
            field=models.DateField(default='', verbose_name='Дата вылета'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='scheduled_departure_time',
            field=models.TimeField(default='', verbose_name='Время вылета'),
        ),
    ]
