# Generated by Django 3.2.8 on 2021-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_auto_20211104_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='url',
            field=models.SlugField(default='', max_length=130),
        ),
    ]
