# Generated by Django 3.2.8 on 2021-11-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_auto_20211123_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='passenger_id',
        ),
        migrations.AddField(
            model_name='tickets',
            name='passenger_last_name',
            field=models.TextField(default='Иванов', max_length=30, verbose_name='Фамилия пассажира'),
            preserve_default=False,
        ),
    ]
