# Generated by Django 3.2.8 on 2021-11-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0005_auto_20211125_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='status',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Busy')], default='F', max_length=1, verbose_name='Статус места'),
            preserve_default=False,
        ),
    ]
